

- [Error Handling](#error-handling)
  - [エラーメッセージを表示](#エラーメッセージを表示)
- [エラー画面からの復帰](#エラー画面からの復帰)

# Error Handling
users/page.tsx ファイルと UserList.tsx ファイルを利用して Error Handling の動作確認を行います。
- users/page.tsx ファイルでは UserList コンポーネントを import しています。

users/page.tsx
```typescript
import UserList from './UserList';

const Page = async () => {
  return (
    <div className="m-4">
      <h1 className="text-lg font-bold">ユーザ一覧</h1>
      <UserList />
    </div>
  );
};

export default Page;
```

UserList.tsx ファイルで fetch 関数によるデータ処理に失敗した場合にエラーを throw させるため response.ok を使って分岐を行います。
- fetch 関数の処理に失敗した場合に response オブジェクトの ok プロパティには false が入ります。

UserList.tsx
```typescript
type User = {
  id: string,
  name: string,
  email: string,
};

const UserList = async () => {
  // await new Promise((resolve) => setTimeout(resolve, 5000));
  const response = await fetch('https://jsonplaceholder.typicode.com/users');
  if (!response.ok) throw new Error('Failed to fetch data');
  const users: User[] = await response.json();
  return (
    <ul>
      {users.map((user) => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
};

export default UserList;
```

fetch 関数の引数で設定している URL を存在しないhttps://jsonplaceholder.typicode.com/userに変更します。
- "users"から"s"を削除して"user"としています。
- 存在しないURLにアクセスを行うとresponse.okの値がfalseになるためErrorがthrowされます。

User ページ(/users)にブラウザからアクセスするとエラーにより Unhandled Runtime Error 画面が表示されます。
![Alt text](https://reffect.co.jp/images/react/next-js-13/next-js-13-4-18-1024x614.webp)

右上に表示されている"X"ボタンをクリックすると画面の左下にボックスが表示され再度"X"をクリックすると先程表示されていた"Unhandled Runtime Error"の画面が表示されます。
![Alt text](https://reffect.co.jp/images/react/next-js-13/next-js-13-4-19-1024x600.webp)

## エラーメッセージを表示
Unhandled Runtime Error 画面ではなくエラーメッセージのみを表示させるように Error Handling の設定を行なっていきます。

users ディレクトリに error.tsx ファイルを作成して以下のコードを記述します。

error.tsx
```typescript
'use client';

export default function Error({ error }: { error: Error }) {
  return (
    <div className="m-4 font-bold">
      <p>{error.message}</p>
    </div>
  );
}
```
Page ディレクトリの直下に error.tsx ファイルを作成すると Next.js が自動で Unhandled Runtime Error が発生した場合にエラーをハンドリングするため error.ts ファイルが利用されます。
- エラーハンドリングには React の ErrorBoundary を利用しており ErrorBoundary タグで page.tsx をラップする形で設定が行われます。

!!! info App Router ではデフォルトではすべてのコンポーネントが Server Component でサーバ側で処理が行われます。
    error.ts ファイルはクライアント(ブラウザ)側で処理を行う必要があるためファイルの先頭に"use client"を追加する必要があります。
    - "use client"を明示的に設定することでコンポーネントが Server Component から Client Component に変わります。

error.tsx ファイルを設定後に users にアクセスすると error.tsx ファイルで設定したメッセージがブラウザ上に表示されます。左下に表示されているボックスの"X"をクリックすると Unhandled Runtime Error の画面が表示されます。
![Alt text](https://reffect.co.jp/images/react/next-js-13/next-js-13-4-20-1024x600.webp)

# エラー画面からの復帰
ここでの設定では存在しない URL を設定しているので何度/users にアクセスしてもエラーが発生します。
- しかし本番では一時的にエラーが発生しているため再度/users にアクセスするとエラーが解消に正常に動作することもあります。
- エラーが解消した場合にエラー画面から復帰するために reset 関数が準備されているので reset 関数の処理を error.tsx ファイルに追加します。

error.tsx
```typescript
'use client';

export default function Error({
  error,
  reset,
}: {
  error: Error,
  reset: () => void,
}) {
  return (
    <div className="m-4 font-bold">
      <p>{error.message}</p>
      <button
        className="px-2 py-1 text-white bg-blue-500 rounded-lg"
        onClick={() => reset()}
      >
        Try again
      </button>
    </div>
  );
}
```

/users にアクセスするとエラーメッセージと"Try again"ボタンが表示されます。
![Alt text](https://reffect.co.jp/images/react/next-js-13/next-js-13-4-21-1024x600.webp)

"Try again"ボタンをクリックしても現在の設定では引き続きエラーが発生するので同じ画面が再表示されます。










